#if UNITY_EDITOR
using UnityEditor;

/// <summary>
/// Tools menu item declarations.
/// </summary>
public class ToolsMenu
{
    /// <summary>
    /// Hit this button to automatically regenerate the autogenerated source files.
    /// </summary>
    [MenuItem("Tools/Rebuild Autogenerated Source Files")]
    private static void RebuildAutogenerated()
    {
        GenerateAnimatorMetadataLookupTable.Refire();
        GenerateDatatableFromBuildSettings.Refire();
    }
}

#endif