// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CnfBattleSys {
    using UnityEngine;
    
    public partial class Battler {
        /// <summary>Passes the given EffectPackage through to the appropriate method to handle applying its effect. Automatically generated.</summary>
        public virtual void ApplyEffect(CnfBattleSys.BattleAction.Subaction.EffectPackage effect) {
            switch (effect.effectType)
            {
                case EffectPackageType.Buff_DamageOutputUp:
                    Buff_DamageOutputUp(effect);
                    break;
                default:
                    Debug.Log("Unhandled EffectPackageType: " + effect.effectType);
                    break;
            }
        }
    }
}
