// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ExtendedAnimationManagement {
    
    /// <summary> Static class containing animator metadata definitions. Automatically generated. </summary>
    public static class AnimatorMetadataLookupTable {
        // <summary> The table of animator metadata. Each animator controller automatically has a MetadataPusher attached to it, which has its index in this table. </summary>
        public static AnimatorMetadata[] lookupTable = new AnimatorMetadata[] {
                new AnimatorMetadata(new AnimatorMetadata.StateMetadata[][] {
                            new AnimatorMetadata.StateMetadata[] {
                                    new AnimatorMetadata.StateMetadata("Base Layer.DecisionConfirm", "DecisionConfirm"),
                                    new AnimatorMetadata.StateMetadata("Base Layer.DecisionShow", "DecisionShow"),
                                    new AnimatorMetadata.StateMetadata("Base Layer.Idle", "Idle"),
                                    new AnimatorMetadata.StateMetadata("Base Layer.Close", "Close"),
                                    new AnimatorMetadata.StateMetadata("Base Layer.Done", "Done")}}, new CnfBattleSys.AnimEventType[0], new int[0][]),
                new AnimatorMetadata(new AnimatorMetadata.StateMetadata[][] {
                            new AnimatorMetadata.StateMetadata[] {
                                    new AnimatorMetadata.StateMetadata("Base Layer.Confirm", "Confirm"),
                                    new AnimatorMetadata.StateMetadata("Base Layer.FailedConfirm", "FailedConfirm"),
                                    new AnimatorMetadata.StateMetadata("Base Layer.Idle", "Idle"),
                                    new AnimatorMetadata.StateMetadata("Base Layer.Selected", "Selected"),
                                    new AnimatorMetadata.StateMetadata("Base Layer.Locked", "Locked"),
                                    new AnimatorMetadata.StateMetadata("Base Layer.Locked+Selected", "Locked+Selected"),
                                    new AnimatorMetadata.StateMetadata("Base Layer.WheelClose", "WheelClose")}}, new CnfBattleSys.AnimEventType[0], new int[0][]),
                new AnimatorMetadata(new AnimatorMetadata.StateMetadata[][] {
                            new AnimatorMetadata.StateMetadata[] {
                                    new AnimatorMetadata.StateMetadata("Base Layer.idle", "idle"),
                                    new AnimatorMetadata.StateMetadata("Base Layer.willPass", "willPass"),
                                    new AnimatorMetadata.StateMetadata("Base Layer.active", "active")}}, new CnfBattleSys.AnimEventType[0], new int[0][]),
                new AnimatorMetadata(new AnimatorMetadata.StateMetadata[][] {
                            new AnimatorMetadata.StateMetadata[] {
                                    new AnimatorMetadata.StateMetadata("Base Layer.spin_forever", "spin_forever")}}, new CnfBattleSys.AnimEventType[0], new int[0][]),
                new AnimatorMetadata(new AnimatorMetadata.StateMetadata[][] {
                            new AnimatorMetadata.StateMetadata[] {
                                    new AnimatorMetadata.StateMetadata("Base Layer.loading", "loading")}}, new CnfBattleSys.AnimEventType[0], new int[0][]),
                new AnimatorMetadata(new AnimatorMetadata.StateMetadata[][] {
                            new AnimatorMetadata.StateMetadata[0]}, new CnfBattleSys.AnimEventType[0], new int[0][]),
                new AnimatorMetadata(new AnimatorMetadata.StateMetadata[][] {
                            new AnimatorMetadata.StateMetadata[] {
                                    new AnimatorMetadata.StateMetadata("Base Layer.Walk", "Walk"),
                                    new AnimatorMetadata.StateMetadata("Base Layer.Wait", "Wait"),
                                    new AnimatorMetadata.StateMetadata("Base Layer.Dead", "Dead"),
                                    new AnimatorMetadata.StateMetadata("Base Layer.Damage", "Damage"),
                                    new AnimatorMetadata.StateMetadata("Base Layer.Attack", "Attack")}}, new CnfBattleSys.AnimEventType[0], new int[0][])};
    }
}
